### PR TITLE
I figured out why the python syntax highlighting wasn't working!

### PR DESCRIPTION
**Pull request by LeptoFlare**
;)

This occurs multiple times throughout the documentation. This is just one scenario that I caught.

### CODE REVIEW

**Comment by rafalp** [comment]
Hi!

Could you also apply this fix to examples in `website/versioned_docs`?

Sorry for late response 🙏

**Comment by LeptoFlare** [comment]
Do mean in every single instance of the `mutations.py` file, for every version?

**Comment by rafalp** [comment]
That would be ideal, but updating code examples in the latest version will do. ;)

**Comment by LeptoFlare** [comment]
Done!

I did it for all versions too.

**Comment by rafalp** [comment]
Great, thanks!

**Pull request merged**
