### PR TITLE
fix:  docs/resolvers

### PR DESCRIPTION
**Pull request by flaviomicheletti**
Hey guys!

I think this example code from the [docs/resolvers](https://github.com/mirumee/ariadne-website/blob/master/docs/resolvers.md?plain=1#L78) page is incorrect.

Screenshot from 2023-01-28 12-15-20

Hope I helped!

### CODE REVIEW

**Comment by rafalp** [comment]
Can you please replace resolver to return a dict instead? I feel that including user class there kinda muddies the whole example, which is supposed to show that you can have multiple `ObjectType`s.

Thank you and sorry for coming late to this!

**Comment by flaviomicheletti** [comment]
Yes, of course!

Is it good now?

**Comment by rafalp** [comment]
Yes. Can you also update versioned copies of this document that are in `versioned_docs` directory? That way this change will appear for old versions of documentation, and not just for next one.

**Comment by flaviomicheletti** [comment]
OK, no problem!

But I'm not sure I understand exactly how it works.

I took a copy of the current version of the `resolver.md.` file.

But I'm not sure if the name of the folder I created was supposed to be `0-18`.

**Comment by rafalp** [comment]
That's not it. :D Please check versions already existing in `versioned_docs` for `resolvers.md` file. If this file exists for given version, see if it also has the issue you've fixed in this PR. If it does, apply your changes to the file as well.

That way your fix will also appear to people checking the docs for past versions, like Ariadne 0.14

**Comment by flaviomicheletti** [comment]
OK, I think I get it (lol)!

Take a look, please.

Now, do I need to delete the `version-0.18` folder?

**Comment by rafalp** [comment]
> Now, do I need to delete the version-0.18 folder?

Yes

**Comment by flaviomicheletti** [comment]
done!

**Comment by rafalp** [comment]
Thank you!

**Pull request merged**
